### ISSUE TITLE
PHP failed with Gitlab Integrated lightweight alternative to Sentry

### ISSUE THREAD

**Issue by EHLOVader** [stayallive/wp-sentry#101]
This may actually be a question about if this will or can support [Gitlab's integrated alternative endpoint to sentry](https://docs.gitlab.com/ee/operations/error_tracking.html#integrated-error-tracking). 
But they say that you can still use the sentry SDK, which this does. 

When I test Javascript with my issued DSN it says it is successful. But the PHP test returns an error that it failed but no other information. 

Was there anywhere to look for logs about what was returned, or any reason explicitly that this might not support the same SDK.

Gitlab's documentation on their integrated error tracking.
https://docs.gitlab.com/ee/operations/error_tracking.html#integrated-error-tracking

**Comment by stayallive** [comment]
Yep, but it's possible that is too late to do it.

GitLab lightweight is not supported by the Sentry PHP SDK (and I suspect never will receive proper support for obvious reasons) so I'm also not going to do anything to make it work in this plugin 😄 

It also looks like they already fixed the compression issues on their side so this might all start working after the next GitLab release.

**Comment by EHLOVader** [comment]
Thanks for the update @stayallive. Gitlab did fix this, so it looks like it is working for me now.
