### ISSUE TITLE
Support for Multisite?

### ISSUE THREAD

**Issue by jordantrizz** [stayallive/wp-sentry#102]
I've installed your plugin on a multisite instance and network activated the plugin. I don't seem to be getting errors in sentry.io

**Comment by stayallive** [comment]
Are you sure you are supposed to get errors? Since it's possible everything just works 😊

**Comment by jordantrizz** [comment]
I thought the same. But I just sent a test via the plugin and nothing showed up at sentry.io :(

**Comment by stayallive** [comment]
Okay, is the test page giving you some random looking event ID and a success message?

Have you also checked if you are not over your quota on sentry.io which will also result in no events coming through!
