### ISSUE TITLE
Interface 'Stringable' not found

### ISSUE THREAD

**Issue by Onatcer** [stayallive/wp-sentry#116]
Hi, 
it looks like the plugin just auto updated for one of my wordpress sites and broke the site because the Sentry SDK uses a PHP 8 Interface and the site is running on 7.3

PHP Fatal error:  Interface 'Stringable' not found in /wp-content/plugins/wp-sentry-integration/build/vendor/sentry/sentry/src/Dsn.php on line 12

I'm not sure if it is a plugin or sdk problem.

**Comment by jaimyvangerrevink** [comment]
@Onatcer I've came across the same problem. Is it possible you had v4.10 installed? v4.10.1 should contain a fix for this problem, also 4.10.3 is already released.

**Comment by Onatcer** [comment]
@jaimyvangerrevink thanks for the pointer, it works with 4.10.3 now. 

sorry for not checking the release notes, i just assumed it was the latest version. 
closing the issue.
