### ISSUE TITLE
JavaScript failed to send test event. 

### ISSUE THREAD

**Issue by ValeSauer** [stayallive/wp-sentry#125]
JS test returns 

> JavaScript failed to send test event. Check your configuration to make sure your DSN is set correctly.

DSNs are set correctly, even the legacy way:

```
define( 'WP_SENTRY_ENV', 'production' );
define( 'WP_SENTRY_PHP_DSN', '...' );
define( 'WP_SENTRY_ERROR_TYPES', E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_USER_DEPRECATED );
define( 'WP_SENTRY_SEND_DEFAULT_PII', false );
define( 'WP_SENTRY_BROWSER_DSN', '...');
define( 'WP_SENTRY_PUBLIC_DSN', '...' );
```

Are there any known interferrences with other plugins or any approaches on debugging this?

**Comment by ValeSauer** [comment]
@stayallive 
My browser console shows

`=> Sending a test message to Sentry...`
```
tools.php?page=wp-sentry:415 !> Failed to sent a test message to Sentry
(anonymous) @ tools.php?page=wp-sentry:415
```
There is no adblocker, tried it even with different machines and with different networks. It does not even start an XHR call.

**Comment by stayallive** [comment]
Hmm, that is not saying much 😅 I'm a bit at a loss here since you seem to do all the things correct.

You can try and run `Sentry.SDK_VERSION` in your console window. It should look something like this:

![image](https://user-images.githubusercontent.com/1090754/159894853-97a88db0-92fa-42b4-8a3f-fe890218f154.png)

If it doesn't then the Sentry JavaScript bundle might not have been loaded at all.

**Comment by ValeSauer** [comment]
@stayallive  Unfortunately Sentry is undefined.
![image](https://user-images.githubusercontent.com/7767250/161274425-02781500-ee31-45f4-b421-1e0e9657f1a7.png)

**Comment by ValeSauer** [comment]
The page is [https://take-a-garden.com](https://take-a-garden.com) Neither frontend nor backend does load any js-file that looks wp-sentry-related. There is no minification plugin, however we use WP Super Cache (but without CDN activated). Enabling and disabling the plugin does not have any effect. I have uninstalled and reinstalled wp sentry: No effect.

Really weird... :-(

**Comment by yashumitsu** [comment]
Hi, I had the same problem, please make sure you have defined variables before _wp-settings.php_ inclusion:

**wp-config.php**:
```
define( 'WP_SENTRY_BROWSER_DSN', ...

require_once ABSPATH . 'wp-settings.php';
```

**Comment by ValeSauer** [comment]
@yashumitsu Thanks! That actually solved it! I'll propose a change to the documentation.

**Comment by stayallive** [comment]
There is no need to propose any changes, you missed this line in your `wp-config.php`:

```
/* That's all, stop editing! Happy publishing. */
```

You should _never_ do anything below that line as it suggests.

(you can see this in the [wp-config.php template file[(https://github.com/WordPress/wordpress-develop/blob/trunk/wp-config-sample.php#L88))

**Comment by ValeSauer** [comment]
Oh right! Make certainly sense.
