### ISSUE TITLE
Sentry.javascript.browser@v7.0.0 is available

### ISSUE THREAD

**Issue by Locheed** [stayallive/wp-sentry#131]
Just noticed the update recommendation on the issue listing in the dashboard.

**Comment by stayallive** [comment]
Yes. It was released 4 days ago, please allow for some time to update the plugin.

**Comment by Locheed** [comment]
Yes of course. No hurry. Just added this here as a to-do ticket.

**Comment by stayallive** [comment]
Went for 7.1.1 but it's now release: https://github.com/stayallive/wp-sentry/releases/tag/v5.0.0
