### ISSUE TITLE
Plugin can't handle Sentry being unreachable

### ISSUE THREAD

**Issue by delellisgabriel** [stayallive/wp-sentry#142]
Hi Alex, my team has been using your plugin in our WP and everything was fine until Sentry went down. This happened to us 6 months ago on Version 4.15.0 and we had to disable the plugin because it unfortunately couldn't handle sentry being unreachable.

I was checking your releases to see if this has been fixed but I don't see it being mentioned in any of the releases. Could you provide me with information about this issue? was it resolved or you guys were unaware of it?

Thanks!

**Comment by stayallive** [comment]
This was addressed in the base PHP SDK in May: https://github.com/getsentry/sentry-php/releases/tag/3.5.0

We reduced the timeouts and retries, it will still have impact but nothing like what happended ~6 months ago.

Hope that answers the question!

**Comment by delellisgabriel** [comment]
yes this answers my question. @stayallive Thank you!
