### ISSUE TITLE
Automated updates for Sentry SDKs

### ISSUE THREAD

**Issue by androidacy-user** [stayallive/wp-sentry#143]
Here we are again, the JavaScript SDK is 7+ versions behind, To be honest, Sentry updates quite frequently, so perhaps some automated workflow to update the JS/PHP SDKs would be a viable option.

Just a thought for consideration, especially as it would mean less time for you to spend updating the SDKs 😄

**Comment by stayallive** [comment]
Thanks, I'll take this into consideration and might implement this in the future.
