### ISSUE TITLE
Session Reply support

### ISSUE THREAD

**Issue by uhlhosting** [stayallive/wp-sentry#152]
Hi,

https://docs.sentry.io/platforms/javascript/session-replay/ this is new recently released to self hosted too. 

according to the docs to deploy it should be very simple:

Adding Session Replay to your Browser JavaScript project is simple. Make sure you've got these basics down.

Install

For the Session Replay to work, you must have the Sentry browser SDK package, or an equivalent framework SDK (e.g. @sentry/react) installed, minimum version 7.27.0.

# Using yarn
`yarn add @sentry/browser`

# Using npm
`npm install --save @sentry/browser`

Configure

Add the following to your SDK config. There are several privacy and sampling options available, all of which can be set using the integrations constructor. Learn more about configuring Session Replay by reading the [configuration docs](https://docs.sentry.io/platforms/javascript/session-replay/).

```
import * as Sentry from "@sentry/browser";

Sentry.init({
  dsn: "https://3c4201a5f51a433b8605c391aee8d4ef@sentry.uhlhost.net/9",

  // This sets the sample rate to be 10%. You may want this to be 100% while
  // in development and sample at a lower rate in production
  replaysSessionSampleRate: 0.1,
  // If the entire session is not sampled, use the below sample rate to sample
  // sessions when an error occurs.
  replaysOnErrorSampleRate: 1.0,

  integrations: [new Sentry.Replay()],
});
Waiting for this project's first user session
```

**Comment by stayallive** [comment]
I'll direct you to #145 for now 👍
