### ISSUE TITLE
Should `admin_enqueue_scripts()` be opt-in, instead of opt-out?

### ISSUE THREAD

**Issue by lkraav** [stayallive/wp-sentry#159]
We were debugging some admin JS slowness, and I noticed integration loads trackers also in wp-admin.

I think we don't have telemetry so might have to do random guessing, but how many people are using Sentry for wp-admin development, vs frontend?

Feels like defaulting to opt-in could be the right move?

Until then, here's an mu-plugin for those interested in opt-out:

```php
<?php
/**
 * Plugin Name: WP Sentry Integration should avoid wp-admin.
 *
 * @since 2023.05.18
 */

namespace MuPlugins;

use WP_Sentry_Js_Tracker;

/**
 * @see `WP_Sentry_Js_Tracker::__construct()`
 */
const WP_SENTRY_INTEGRATION_ADMIN_ENQUEUE_PRIORITY = 0;

add_action( 'admin_enqueue_scripts', static function(): void {
    remove_action( 'admin_enqueue_scripts', [ WP_Sentry_Js_Tracker::get_instance(), 'on_enqueue_scripts' ], WP_SENTRY_INTEGRATION_ADMIN_ENQUEUE_PRIORITY );
}, WP_SENTRY_INTEGRATION_ADMIN_ENQUEUE_PRIORITY - 1 );
```

**Comment by stayallive** [comment]
Tracking JS errors in the front-end is as interesting as in the back-end IMHO 😄 

Also at this point opt-in is not an option unless we do a major release, so maybe in the future but at this moment I don't see that that is needed. But happy to add a nicer option than what you have as mu-plugin to disable it in the backend because you also break the tester page with that (although probably not an issue for you).

You mention 6.14.0 specifically in the title, is that because you think it's since that version? Because I think this behaviour has been present for as long as we have the Browser SDK added.

**Comment by lkraav** [comment]
> Tracking JS errors in the front-end is as interesting as in the back-end IMHO 😄 

Depends. Could also be considered as pure noise, as there might not be any bandwidth to address anything at wp-admin layer anyway.

> Also at this point opt-in is not an option unless we do a major release, so maybe in the future but at this moment I don't see that that is needed. But happy to add a nicer option than what you have as mu-plugin to disable it in the backend because you also break the tester page with that (although probably not an issue for you).

Yeah I didn't QA tester page. Perhaps enqueue method could be better split, because ideally tester page would remain working in all cases, indeed.

> You mention 6.14.0 specifically in the title, is that because you think it's since that version? Because I think this behaviour has been present for as long as we have the Browser SDK added.

In this case it's about «latest I tested with».

**Comment by stayallive** [comment]
So I have been thinking what about:

```php
define( 'WP_SENTRY_BROWSER_DSN', 'JS_DSN' );
define( 'WP_SENTRY_BROWSER_ADMIN_ENABLED', true );    //   is_admin()
define( 'WP_SENTRY_BROWSER_FRONTEND_ENABLED', true ); // ! is_admin()
```

Of course we keep the tester page working no matter what you choose here (unless you set no DSN at all).

What do you think?

**Comment by lkraav** [comment]
Sounds about right.

`is_admin()` has some worms in the can with it alsomatching `admin-ajax.php`.

See the fun at `WooCommerce::is_request()` https://github.com/woocommerce/woocommerce/blob/5d6b3d5ceb6c263bbf29c608a4faacf6ea9a8f7c/plugins/woocommerce/includes/class-woocommerce.php#L383-L400 for reference.

**Comment by stayallive** [comment]
Well yeah okay poor wording on my part.

I'd actually use `admin_enqueue_scripts` vs. `wp_enqueue_scripts` 😄 

Should work to allow you to disable it on the admin side by setting `WP_SENTRY_BROWSER_ADMIN_ENABLED` to `false`.

If you would be helped by that I will work to implement that!

**Comment by stayallive** [comment]
[v6.15.0](https://github.com/stayallive/wp-sentry/releases/tag/v6.15.0) was just released adding these constants, hope that allows you to easily enable the Sentry SDK where you need or want it.
