### ISSUE TITLE
a way to track WP_Error problems 

### ISSUE THREAD

**Issue by senadir** [stayallive/wp-sentry#16]
I use wp_error in my code, is there anyway to detect it?

**Comment by stayallive** [comment]
Could you give a more specific example? What er you doing with the WP_Error, do you want to log it to Sentry or what are you trying to achieve?

**Comment by senadir** [comment]
I'm developing a plugin, when an error happens (e.g. invalid value passed to a function) I return a WP_Error, what's the best way to track it? I've switched to Excpetions now, can I still use it?

**Comment by stayallive** [comment]
Hey @senadir with uncaught exceptions there is nothing you have to do to get them to show up in Sentry because Sentry will catch those for you. 

If you are catching the exceptions you will have to submit them manually like this for example:

```php
try {
    throw new Exception('Test exception');
} catch (Exception $e) {
    // Safety check just in case the plugin is not available or disabled
    if ( class_exists( 'WP_Sentry_Php_Tracker' ) ) {
        $sentryClient = WP_Sentry_Php_Tracker::get_instance()->get_client()->captureException( $e );
    }
}
```
