### ISSUE TITLE
CURLOPT_TIMEOUT

### ISSUE THREAD

**Issue by AlexWebpuro** [stayallive/wp-sentry#160]
PHP Fatal error:  Uncaught Error: Undefined constant "CURLOPT_TIMEOUT" in /wp-content/plugins/wp-sentry-integration/build/vendor/sentry/sentry/src/HttpClient/HttpClientFactory.php:108.

How I can resolve this, when I run the wp cli doesn't work and appear this error log.

Thanks for your help.

**Comment by stayallive** [comment]
Hi @AlexWebpuro is it possible your PHP installation doesn't have the cURL extension installed?

**Comment by stayallive** [comment]
Awesome, glad you got it solved 😎
