### ISSUE TITLE
Button not firing the event when using wp-sentry, working if wp-sentry is disabled

### ISSUE THREAD

**Issue by erip2** [stayallive/wp-sentry#178]
Hi there and firstly thank you for the plugin! It has worked seamlessly.

For the last weeks I noticed a problem that is very specific and I don't know how you can help, but I decided to ask anyway.

So, in this website (www.galialahav.com) we have the cookies banner. In mobile, the button "I accept" doesn't fire the event it's supposed to, or sometimes you have to click it many times until the banner is hidden.

If I disable the plugin, this works as intended, but with `wp-sentry` activated, what I mentioned above happens.

**Comment by stayallive** [comment]
Interesting, I have just tried it, but the button disappears immediately for me. There is probably a very logical reason for this but there shouldn't be any side-effect from having the JS SDK loaded on your page. You can try to open an issue on the JS SDK: https://github.com/getsentry/sentry-javascript/issues or jump into Discord (https://discord.com/invite/sentry) to see if you can dig something up.

But unless you are seeing errors in your browser console (or Sentry) when clicking the button I don't think there is anything wrong with the very thin wrapper we have here around the JS SDK.

**Comment by erip2** [comment]
Oh, that is because I have disabled the plugin for now. Enabled it again.

Anyway, thank you, I'll try to write to the sentry team :)

**Comment by stayallive** [comment]
Just tried it again to be sure but not seeing any issues, but it might be browser specific, I am on Firefox.
