### ISSUE TITLE
Not seeing database/queries info in Sentry

### ISSUE THREAD

**Issue by travstone** [stayallive/wp-sentry#185]
As title suggests, have set up the plugin on a number of sites, and am getting back and front end code data (php/js). However, all of the reporting on DB performance and queries is completely empty. Does the plugin not support that functionality, or do I need to  do something special to enable it? Apologies if this is in the docs somewhere, I looked/searched but didn't turn up anything promising.

**Comment by stayallive** [comment]
Yes, this is not supported yet in this plugin. You can follow this discussion for updates: https://github.com/stayallive/wp-sentry/discussions/113
