### ISSUE TITLE
Duplicate error reporting

### ISSUE THREAD

**Issue by lightstrike** [stayallive/wp-sentry#19]
Thank you for creating this plugin @stayallive, it's helped me already 😄 

I am just doing PHP tracking right now, using the following settings: 
```php
define('WP_SENTRY_DSN', env('WP_SENTRY_DSN'));
define('WP_SENTRY_ERROR_TYPES', E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_USER_DEPRECATED);
define('WP_SENTRY_ENV', env('WP_ENV'));
```

One thing I'm noticing on my side is the duplicate reporting of errors in Sentry:

![screenshot 2017-11-07 at 10 25 14](https://user-images.githubusercontent.com/1368742/32501650-8d14a632-c3a6-11e7-8e9a-53770286ed8a.png)

Any ideas how I can eliminate the duplicate issue?

**Comment by stayallive** [comment]
Hey @lightstrike, happy to hear you like it 😃 

This is actually an issue in the Sentry PHP SDK (getsentry/sentry-php#408) and we are in the process of finding a good reproducable case since this does not happen always, you might have given me one 😄

Just to confirm, you are running PHP 7.0+?

**Comment by lightstrike** [comment]
Yes, I'm using trellis, [which installs PHP 7.1](https://github.com/roots/trellis/blob/master/roles/php/tasks/main.yml#L7).

**Comment by stayallive** [comment]
Thanks @lightstrike, I'll let you know when it's fixed!

**Comment by stayallive** [comment]
`v2.1.3` was just releaased to the WP plugin repository.

Let me know if the problem persists in that version.

**Comment by lightstrike** [comment]
Excellent, thanks @stayallive! I'll check and let you know.
