### ISSUE TITLE
PHP 8.3 warning

### ISSUE THREAD

**Issue by rafaucau** [stayallive/wp-sentry#191]
This warning is displayed when `WP_DEBUG_DISPLAY` is enabled:
> Deprecated: Creation of dynamic property WPSentry\ScopedVendor\GuzzleHttp\Psr7\CachingStream::$stream is deprecated in /*****/web/app/plugins/wp-sentry-integration/build/vendor/guzzlehttp/psr7/src/CachingStream.php on line 28

**Comment by dingo-d** [comment]
Same for me, but this is not the fault of the plugin, but the SDK (well, the Guzzle PSR7 dependency actually).

**Comment by stayallive** [comment]
This issue is:

```
guzzlehttp/psr7 2.6.2 requires php (^7.2.5 || ^8.0 but 7.2.0 is installed)
```

I guess we can bump our minimum PHP version to 7.2.5 as well instead of 7.2.0.

**Comment by dingo-d** [comment]
I don't think it can hurt 👍🏼

**Comment by stayallive** [comment]
https://github.com/stayallive/wp-sentry/releases/tag/v7.15.0 was just released which updates `guzzlehttp/psr7`. This should resolve the issue, feel free to re-open if not.
