### ISSUE TITLE
Tracing: Uncaught Error: Class "GuzzleHttp\Psr7\ServerRequest" not found 

### ISSUE THREAD

**Issue by saas786** [stayallive/wp-sentry#194]
```[03-Jul-2024 14:25:03 UTC] PHP Fatal error:  Uncaught Error: Class "GuzzleHttp\Psr7\ServerRequest" not found in \wp-content\plugins\wp-sentry-integration\src\tracing\class-wp-sentry-php-tracing.php:85
Stack trace:
#0 \wp-content\plugins\wp-sentry-integration\src\tracing\class-wp-sentry-php-tracing.php(64): WP_Sentry_Php_Tracing->start_transaction(Object(Sentry\State\Hub))
#1 \wp-content\plugins\wp-sentry-integration\src\tracing\class-wp-sentry-php-tracing.php(30): WP_Sentry_Php_Tracing->__construct()
#2 \wp-content\plugins\wp-sentry-integration\wp-sentry.php(119): WP_Sentry_Php_Tracing::get_instance()
#7 {main}
  thrown in \wp-content\plugins\wp-sentry-integration\src\tracing\class-wp-sentry-php-tracing.php on line 85
```

**Comment by saas786** [comment]
Quick troubleshooting: It appears the issue is caused by unprefixed references to code, while Composer loads prefixed vendors due to PHP-Scoper.

![phpstorm64_FaFDwmmDkL](https://github.com/stayallive/wp-sentry/assets/1642796/5d4e4e0b-e014-4678-b9bb-a85ae1b6fa36)
![phpstorm64_Oi6eK2BYD5](https://github.com/stayallive/wp-sentry/assets/1642796/84c84cab-81be-4088-86d8-00d73656588c)

**Comment by stayallive** [comment]
That's not good. Let me see what is going on there...

**Comment by stayallive** [comment]
Thanks for your detailed report, found it quickly and added a fix.

https://github.com/stayallive/wp-sentry/releases/tag/v7.17.1 is out and should fix the issue!

**Comment by saas786** [comment]
I can see your workaround.

However, you should properly prefix your code instead of using conditional prefixes.

Reference: https://github.com/stayallive/wp-sentry/blob/303a1916612220856892e0db34a14d7e1f02f94c/src/tracing/class-wp-sentry-php-tracing.php#L283

If you are interested, I can update PHP-Scoper to the latest version and ensure your code is properly prefixed, eliminating the need for conditional checks.

**Comment by stayallive** [comment]
This plugin can also be installed without prefix using composer for projects that do that and also local development is easier this way. I agree this isn't optimal but it also isn't too bad (yet).
