### ISSUE TITLE
Warning: Undefined variable $php_rofiling_enabled

### ISSUE THREAD

**Issue by leadoux** [stayallive/wp-sentry#197]
I'm seeing the following error when using version 7.17.3 of the WordPress Sentry plugin.

`Warning: Undefined variable $php_rofiling_enabled`.

![Untitled](https://github.com/stayallive/wp-sentry/assets/6283373/da48a9a1-fa1d-40ab-a000-1151cd6e4929)

**Comment by leadoux** [comment]
Fix is in the pull request https://github.com/stayallive/wp-sentry/pull/196

**Comment by stayallive** [comment]
Appreciate the report & PR, thanks ❤️
