### ISSUE TITLE
ExcimerProfiler not found when enabling profiling

### ISSUE THREAD

**Issue by rieschl** [stayallive/wp-sentry#198]
It seems that there is some issue with autoloading all classes.
When setting the `WP_SENTRY_PROFILES_SAMPLE_RATE` constant everytime a profile is to be made the application generates an error:
`Uncaught Error: Class "WPSentry\\ScopedVendor\\ExcimerProfiler" not found in [...]/wp-content/plugins/wp-sentry-integration/build/vendor/sentry/sentry/src/Profiling/Profiler.php:66`

Thanks for your help!

**Comment by stayallive** [comment]
Ah, another fun prefix bug 🙈

I've pushed https://github.com/stayallive/wp-sentry/releases/tag/v7.20.0, let me know if that solves it correctly!

**Comment by rieschl** [comment]
> Ah, another fun prefix bug 🙈
> 
> I've pushed https://github.com/stayallive/wp-sentry/releases/tag/v7.20.0, let me know if that solves it correctly!

ah it seems that `7.20` works now as expected. Thanks for the quick fix!

**Comment by stayallive** [comment]
Cool, thanks for the quick test!
