### ISSUE TITLE
Browser failed to send test. Check your configuration to make sure your DSN is set correctly.

### ISSUE THREAD

**Issue by nachogrxdev** [stayallive/wp-sentry#199]
I'm trying to configure Browser Javascript and I'm getting this error when testing.

`Browser failed to send test. Check your configuration to make sure your DSN is set correctly.`

I have run the tests incognito without any extension.

```
// It's possible your WordPress installation is different, check to make sure this path is correct for your installation
require_once __DIR__ . '/wp-content/plugins/wp-sentry-integration/wp-sentry.php';

/** Set up Sentry */
define('WP_SENTRY_PHP_DSN', 'https://XXXXX.ingest.de.sentry.io/XX');
define('WP_SENTRY_SEND_DEFAULT_PII', true);
define('WP_SENTRY_TRACES_SAMPLE_RATE', 0.7); // traces_sample_rate
define('WP_SENTRY_PROFILES_SAMPLE_RATE', 0.7);
define('WP_SENTRY_TRACING_FEATURES', [
        'db' => [
                'spans' => true,
                'breadcrumbs' => defined( 'SAVEQUERIES' ) && SAVEQUERIES,
        ],
        'http' => [
                'spans' => true,
                'breadcrumbs' => true,
        ],
        'transients' => [
                'spans' => true,
                'breadcrumbs' => true,
        ],
]);


define( 'WP_SENTRY_BROWSER_DSN', 'https://XXXXX.ingest.de.sentry.io/XX' );

/* That's all, stop editing! Happy publishing. */
```

**Comment by stayallive** [comment]
Does your network tab make a request out to Sentry? Does that fail?

**Comment by stayallive** [comment]
Okay, you might need to inspect your HTML to see if the Sentry SDK is even loaded. 

There might be a conflict with another plugin or some optimization plugin causing issues.

You would expect to see: `wp-content/plugins/wp-sentry/public/wp-sentry-browser.min.js` being loaded on your page. If that script is not loaded it could explain why there are no other errors or requests visible.

**Comment by stayallive** [comment]
Interesting. It works like a charm on a few of my installations.

What version of PHP, the plugin and/or WordPress are you using?

And is the installation a network installation or regular.

Anything else that might be different or non-standard that you can think of (maybe a theme)?

**Comment by stayallive** [comment]
The plot thickens, interesting. On what WordPress version are you?

You both don't have `WP_SENTRY_BROWSER_ADMIN_ENABLED` defined right?

**Comment by Nachooc5** [comment]
> The plot thickens, interesting. On what WordPress version are you?
> 
> You both don't have `WP_SENTRY_BROWSER_ADMIN_ENABLED` defined right?

![image](https://github.com/user-attachments/assets/307a03ed-a6f7-48f9-a285-061f2d1f5e89)


```php
/* Set Sentry configuration */

// It's possible your WordPress installation is different, check to make sure this path is correct for your installation
require_once __DIR__ . '/wp-content/plugins/wp-sentry-integration/wp-sentry.php';

define('WP_SENTRY_PHP_DSN', 'https://X@X.ingest.us.sentry.io/X');
define('WP_SENTRY_SEND_DEFAULT_PII', true);
define('WP_SENTRY_TRACES_SAMPLE_RATE', 0.7); // traces_sample_rate
define('WP_SENTRY_PROFILES_SAMPLE_RATE', 0.7);

define('WP_SENTRY_BROWSER_DSN', 'https://X@X.ingest.us.sentry.io/X');
define('WP_SENTRY_BROWSER_TRACES_SAMPLE_RATE', 0.7); // tracesSampleRate
// These options are injected into the `Sentry.init()` call
// https://docs.sentry.io/platforms/javascript/session-replay/configuration/#general-integration-configuration
define('WP_SENTRY_BROWSER_REPLAYS_SESSION_SAMPLE_RATE', 0.1); // replaysSessionSampleRate
define('WP_SENTRY_BROWSER_REPLAYS_ON_ERROR_SAMPLE_RATE', 1.0); // replaysOnErrorSampleRate

/* That's all, stop editing! Happy publishing. */
```

This is the configuration of this last Dreamhost environment that I mention. I don't have any definition for the variable commented out by `WP_SENTRY_BROWSER_ADMIN_ENABLED`

**Comment by stayallive** [comment]
Move your `require_once` to AFTER your `define` statements 😅 

The issue is that your config is not defined when you are loading Sentry.

However the admin page loads a lot later and thus picks up on the config just fine.

I have to think of a good way to detect this better 🤔
