### ISSUE TITLE
Pass regex to JS

### ISSUE THREAD

**Issue by combs** [stayallive/wp-sentry#20]
Hello! Thank you for making this plugin. 

We are trying to pass `whitelistUrls` with a `wp_sentry_public_options` filter. The best way to use this option seems to be with regexes:
https://docs.sentry.io/clients/javascript/tips/

But `wp_localize_script` only supports passing bare strings to JS, so our regexes in php seem to make it through with double quotes around 'em in the sentry options object. Then they are parsed as exact match strings.

Is there an easy way to fix? 

I guess it could be a little middleware js, something like, is the first char of the value a '/' or other regex delimiter; if so, parse as new `RegExp()` object. or would that be brittle/unpredictable?

**Comment by stayallive** [comment]
Hey @combs, really sorry I not responded earlier. Totally snowed under and forgot about it 😟 

You are correct that it's not possible to pass a regex which is a bit of a problem. We are currently passing the options using `wp_localize_script` which basicly `json_encodes` the array of options.

Not sure how to make this work with regexes or how to efficiently parse the options (and nested options) to find and initialize the regexes. If you have any ideas please let me know.

I was thinking of doing it all in the browser and looping over all the options and their values and/or nested arrays/objects to find and parse any regex strings (maybe even prepended by `regex:` and converting them.
