### ISSUE TITLE
Feature Request: Implement tracing for HTTP requests which are sent via Wordpress HTTP client

### ISSUE THREAD

**Issue by LordSimal** [stayallive/wp-sentry#203]
Wordpress has quite some nice events to attach this sentry feature (at least it looks to me that way)

https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/Requests/src/Requests.php#L455-L471

So it would be very nice if this plugin would implement https://docs.sentry.io/platforms/php/tracing/instrumentation/requests-module/

**Comment by stayallive** [comment]
It already does. What is not working for you?

**Comment by LordSimal** [comment]
Thanks for the quick response.

Maybe I am too stupid to see it but do I have to set a specific constant in the wp-config.php to enable that feature?

Currently we just add this
```
define( 'WP_SENTRY_PHP_DSN', '--Sentry-DSN-URL--' );
if (file_exists(__DIR__ . '/wp-content/plugins/wp-sentry-integration/wp-sentry.php')) {
    require_once __DIR__ . '/wp-content/plugins/wp-sentry-integration/wp-sentry.php';
}
```

Do we need to enable tracing and therefore set the `WP_SENTRY_TRACES_SAMPLE_RATE`?

**Comment by stayallive** [comment]
Yes, absolutely. Tracing is _not_ enabled by default. So you'd need to set a sample rate for tracing to kick-in. Don't forget to place it just below your DSN and not after the `require_once` 😄 

See: https://github.com/stayallive/wp-sentry#set-up-tracing

**Comment by LordSimal** [comment]
Thank you 🙇🏻
