### ISSUE TITLE
js-sdk-loader uses wrong dsn

### ISSUE THREAD

**Issue by Miracusa** [stayallive/wp-sentry#204]
The script to load the js-sdk-loader uses the PHP-DSN (wich only returns a "The Sentry loader you are trying to use isn't working anymore, check your configuration."-Error) instead of the Browser-DSN wich would return a correct script.

**Comment by stayallive** [comment]
Excuse me, what js-sdk-loader are you talking about exactly? Can you share some code/configuration? This plugin doesn't make use of the JS SDK loader script.

**Comment by Miracusa** [comment]
It dos not? 
If i view the source of the pages I have this peace of script in it since I configured the WP_SENTRY_BROWSER_REPLAYS_SESSION_SAMPLE_RATE etc.
<script
  src="http://[[sentry-url]]/js-sdk-loader/[[PHP-DSN]].min.js"
  crossorigin="anonymous"></script>

I have this in the wp-config:

define( 'WP_SENTRY_PHP_DSN', 'http://[[PHP-DSN]]@[[sentry-url]]/6' );
define( 'WP_SENTRY_BROWSER_DSN', 'http://[[JavaScript-DSN]]@[[sentry-url]]/7' );

define('WP_SENTRY_BROWSER_ADMIN_ENABLED', true);
define('WP_SENTRY_BROWSER_LOGIN_ENABLED', true);
define('WP_SENTRY_BROWSER_FRONTEND_ENABLED', true);
define( 'WP_SENTRY_SEND_DEFAULT_PII', true );
define( 'WP_SENTRY_ERROR_TYPES', E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_USER_DEPRECATED & ~E_USER_NOTICE );
define( 'WP_SENTRY_TRACES_SAMPLE_RATE', 1.0 ); //0.3
define( 'WP_SENTRY_BROWSER_TRACES_SAMPLE_RATE', 1.0 ); //0.3
define( 'WP_SENTRY_BROWSER_REPLAYS_SESSION_SAMPLE_RATE', 1.0 ); //0.1
define( 'WP_SENTRY_BROWSER_REPLAYS_ON_ERROR_SAMPLE_RATE', 1.0 );

**Comment by stayallive** [comment]
No, an example of scripts this plugin outputs:

```html
<script src="https://wordpress.develop/wp-content/plugins/wp-sentry/public/wp-sentry-browser.tracing.replay.min.js?ver=8.1.0" id="wp-sentry-browser-bundle-js"></script>
<script id="wp-sentry-browser-js-extra">
var wp_sentry = {"wpBrowserTracingOptions":{"enableInp":true},"tracesSampleRate":"1","wpSessionReplayOptions":{},"replaysSessionSampleRate":"0","replaysOnErrorSampleRate":"1","wpBrowserFeedbackOptions":{"enabled":true},"environment":"production","release":"1.2","context":{"user":{"id":1},"tags":{"wordpress":"6.6.1","language":"nl-NL"}},"dsn":"https:\/\/xxx@o123.ingest.example.com\/123"};
</script>
<script src="https://wordpress.develop/wp-content/plugins/wp-sentry/public/wp-sentry-init.js?ver=8.1.0" id="wp-sentry-browser-js"></script>
```

So considering your configuration you might be loading Sentry twice 😅

Notice that all our scripts have an `id` that starts with `wp-sentry`. The script tag you mentions doesn't have that so I think that is coming from somewhere else.

**Comment by Miracusa** [comment]
hm, seems right. the wp-sentry-browser-bundle-js is present. Interesting. Could this be the resson why no replays are sampled?

**Comment by stayallive** [comment]
It can be because the other SDK you are loading via the SDK loader is conflicting I would advise removing that first. Other reasons can be having an adblocker enabled or being over the quota of your paid plain.

**Comment by Miracusa** [comment]
Ah, will try that. Allready found it and indeed there was a second one beeing loaded...
What paid plan?

**Comment by stayallive** [comment]
If you are on sentry.io you are either on a free plan or paid plan (https://sentry.io/pricing/) which includes a limited amount of replays each month. If you are self hosting Sentry that is of course not an issue.

**Comment by Miracusa** [comment]
ok. its self hosting.
