### ISSUE TITLE
Sentry - Ignore errors, external urls

### ISSUE THREAD

**Issue by cezarpopa** [stayallive/wp-sentry#208]
Hi Alex,

I hope all is well. 

I’m aware that Sentry has a feature to ignore errors from external URLs and certain patterns. 

I couldn’t find a way to make use of that functionality within the plugin.

Is that feature currently supported? If not, could we consider adding an option to enable this directly through the plugin via some sort of admin menu or similar?

I could potentially have a look at implementing that if new features/prs are welcome.

Thanks,
Cezar

**Comment by cezarpopa** [comment]
Thank you, I am sorry for not being clear with what I am trying to achieve.

On the frontend certain external libraries may have errors of their own which are not really that relevant and honestly can use a lot of quota.

What I am simply looking for is a method to change the Sentry sdk as seen here https://docs.sentry.io/platforms/javascript/configuration/filtering/#filtering-error-events so that I can exclude certain libraries or events in the init.

I hope it makes sense now.

**Comment by stayallive** [comment]
Yeah, for sure!

See: https://github.com/stayallive/wp-sentry?tab=readme-ov-file#wp_sentry_public_options-array

Just like `denyUrls` in the example you can set `ignoreErrors` the same way.

**Comment by cezarpopa** [comment]
Ohh, it is possible! 

I missed that somehow when I had a look in the morning, probably needed more coffee; In which case this issue can be closed.

Thank you!

**Comment by stayallive** [comment]
No worries, it happens. Enjoy the ☕
