### ISSUE TITLE
public_dsn and _dsn

### ISSUE THREAD

**Issue by mikevanegmond** [stayallive/wp-sentry#25]
What seems to be the difference, I have a hard time finding which is which in Sentry.io.
When I place the DSN as SENTRY_PUBLIC_DSN and set the the secret key in SENTRY_DSN (as part of the URL) I can see 'raven' in the source code on the homepage, but it also displays my admin username and admin email address. Is that supposed to work like that?

Any help would be greatly appreciated.

**Comment by stayallive** [comment]
Closing this since I think it's been explained 😄 

If not feel free to re-open.

In v3.0 of the plugin these 2 values will be combined since the (private) DSN is deprecated.

**Comment by tylertadej** [comment]
I'm having an issue related to this question and have posted a support question here: https://wordpress.org/support/topic/dsn-and-public_dsn-the-same/

After looking at the source code here I'm not sure why my setup isn't working. I did notice that the PHP DSN and JS DSN are loaded a bit differently, but it doesn't look like a problem.

**Comment by chrillep** [comment]
Shouldnt the readme reflect that private and public DSN is no more?

**Comment by stayallive** [comment]
From the docs:

```php
// (Optionally) track PHP errors by adding this snippet to your wp-config.php 
// and replace PHP_DSN with your actual DSN that you find in Sentry:
define( 'WP_SENTRY_DSN', 'PHP_DSN' );

// (Optionally) track JavaScript errors by adding this snippet to your wp-config.php
// and replace JS_DSN with your actual public DSN that you find in Sentry (never use your private DSN):
define( 'WP_SENTRY_PUBLIC_DSN', 'JS_DSN' );
```

The naming could do better but it can still be 2 DSN's, the PHP one just doesn't have to include the secret key anymore (as it's deprecated indicated in the Sentry interface), and for the JS the warning "never use your private DSN" still rings true, it's deprecated but the private key in the DSN string still holds value and should never be used in the public one and it still can be used in the PHP one if you wanted.

Happy to accept a PR if you feel the README is incorrect or unclear.

**Comment by rtpHarry** [comment]
FYI this wording did catch me out as a new user.

**Comment by stayallive** [comment]
I have changed the wording in the hopes of making this more clear for new users in the future.

The DSN constants are now named: `WP_SENTRY_PHP_DSN` and `WP_SENTRY_BROWSER_DSN` (the old names are still supported but the new names will be preferred in the docs).

Hope that helps clear up possible confusion around having 2 DSN's with less descriptive names.
