### ISSUE TITLE
2.6.0: Sentry JS v4 crashes browsers in some cases

### ISSUE THREAD

**Issue by lkraav** [stayallive/wp-sentry#26]
See https://github.com/getsentry/sentry-javascript/issues/1707 for details.

Not sure if there's anything to be done here in this repo, but probably good to know regardless. If upstream fixes it, gotta push a release out here for sure.

**Comment by stayallive** [comment]
Ah dang, that's a shame! As soon as there is an update for it I will update this package 👍 thanks for bringing it to my attention!

**Comment by stayallive** [comment]
Yep https://github.com/stayallive/wp-sentry/releases/tag/v2.6.1.

Currently being deployed to the WP plugins repo.

I'll let you close this issue once you can confirm it fixes it 👍

**Comment by stayallive** [comment]
Did not hear back so going to assume this was fixed 👍

**Comment by lkraav** [comment]
Yep, I've not seen any weirdness since you launched 2.6.1. Thanks!
