### ISSUE TITLE
Sentry PHP 2.0 upgrade

### ISSUE THREAD

**Issue by lkraav** [stayallive/wp-sentry#29]
Looks like a significant list of changes https://github.com/getsentry/sentry-php/blob/2.0.0-beta1/UPGRADE-2.0.md but nothing overwhelming on surface. Wdyt?

**Comment by stayallive** [comment]
I'm going to wait until a stable is released 😄 

There is still much discussion going on and some breaking changes coming in `beta2`.

But it's not too bad since we don't have an extreme integration, but does require some thought and a new major version since this is a pretty big change for people using the Sentry client provided by the plugin in their own code.

**Comment by lkraav** [comment]
Badabum https://github.com/getsentry/sentry-php/blob/2.0.0/UPGRADE-2.0.md looks official now :fireworks:

**Comment by stayallive** [comment]
Jep we just tagged `2.x`. 

Will start work on bringing this to `2.x` soon 👍

**Comment by lkraav** [comment]
Hi again. How's this going thus far?

**Comment by stayallive** [comment]
@lkraav as you probably noticed it is not going at all so far (because of lack of time) 👎 

I am going to make some progress on it this week and probably have a PR open soon so you can test with it.

**Comment by stayallive** [comment]
And now the new version is available in `master`. Will be released somewhere in the coming days as 3.0 (which contains the 2.x PHP SDK and the 5.x Browser SDK).

**Comment by lkraav** [comment]
> And now the new version is available in master. Will be released somewhere in the coming days as 3.0 (which contains the 2.x PHP SDK and the 5.x Browser SDK).

Curious, did that 3.0 idea manage to move towards materialization?

**Comment by stayallive** [comment]
No 😞 

I have not had the time to properly test my release, so it's coming but unfortunately I thought I had more time to really test it.

It is all in master in case you feel adventurous 😉
