### ISSUE TITLE
WP 5.2 WSOD protection will cause PHP Notices

### ISSUE THREAD

**Issue by lkraav** [stayallive/wp-sentry#30]
Details https://core.trac.wordpress.org/ticket/46882#comment:7

> It looks like this was because an mu-plugin was loading the currently active theme before `wp_cookie_constants` was defined. This also occurs before `register_theme_directory()` is called, so perhaps it could be thought of as a bug in the plugin.

> We could try and account for this situation by checking if `muplugins_loaded` has been fired before checking if the theme is paused in `WP_Theme::__construct`. I think this might mean that the admin UI when the theme was paused might not be correct since the theme error would never be set.

**Comment by stayallive** [comment]
I am not sure what you would want me to change in this plugin to account for that.

If the core produces a notice we will capture it, not matter the context.

Did you had something specific in mind?

**Comment by lkraav** [comment]
I think core decided already it's more their problem.

**Comment by stayallive** [comment]
Yes, it is. We're not here to cover up notices generated by anything 🙈

There are hooks to do it yourself ofcourse if you wanted to.
