### ISSUE TITLE
Understanding what gets reported

### ISSUE THREAD

**Issue by whysthatso** [stayallive/wp-sentry#37]
I'm trying to understand what gets reported from my errors. i'm running the plugin on a diverse set of wordpress sites, and whatever gets reported feels a bit random to me

for the setup
i would like to get everything, so i set
```
define( 'WP_SENTRY_ERROR_TYPES', E_ALL );
```
furthermore i run two sites per DSN, a production site and a stage site, which i differentiate like so
on production
```
define( 'WP_SENTRY_ENV', 'production' );
```
on stage
```
define( 'WP_SENTRY_ENV', 'stage' );
```

these are some messages that did not get send, but i am not sure why

```
WordPress database error Duplicate entry 'event' for key 'slug' for query INSERT INTO `wp_terms` (`name`, `slug`, `term_group`) VALUES ('event', 'event', 0) made by do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, _wp_batch_split_terms, _split_shared_term
```
```
[27-Aug-2019 07:58:50 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_header() in <snip>/index.php:1
Stack trace:
#0 {main}
  thrown in <snip>/index.php on line 1
```
```
[27-Aug-2019 09:20:07 UTC] PHP Notice:  Trying to get property of non-object in <snip>/functions.php on line 121
```
```
[27-Aug-2019 09:26:48 UTC] PHP Warning:  Parameter 2 to qtranxf_postsFilter() expected to be a reference, value given in <snip>/class-wp-hook.php on line 286
```

i've also tried to add the `add_filter` - example that was mentioned in another issue to throw an exception, but that does not get recorded either. i've also added the plugin as a `must-use`, and i can send foobar events via curl from the command line.

could i test anything else?

**Comment by stayallive** [comment]
Assuming you have it enabled as a must-use plugin and those errors all occur after that must-use plugin was loaded (WordPress does some work before loading plugins) they should all have been reported on. There are a few things that come to mind.

But first I want to rule something out, are you using sentry.io or an on-premise install?

**Comment by whysthatso** [comment]
this is a self-hosted setup.

**Comment by stayallive** [comment]
Which Sentry version are you running?

**Comment by whysthatso** [comment]
Sentry 9.1.1

**Comment by stayallive** [comment]
Hi @whysthatso, I am sorry I never responded to this issue and we did not investigate further, since 2019 we have released a massive amount of updates and hopefully any error you did had was fixed by one of those.

If this issue still persists feel free to re-open/open up a new issue so I can take a closer look again.

**Comment by whysthatso** [comment]
no worries. thanks for all your work :)
