### ISSUE TITLE
Uncaught Symfony\Component\OptionsResolver\Exception\InvalidOptionsException

### ISSUE THREAD

**Issue by hossein** [stayallive/wp-sentry#40]
Hi. I'm following the Read Me instructions to configure a must-use plugin that references the main plugin. However it seems in this case WP_SENTRY_VERSION is not calculated correctly which results in the the mentioned Sentry error frequently ([JSON dump](https://github.com/stayallive/wp-sentry/files/3778330/event.zip)).

The workaround is to hardcode a value [for the release field here](https://github.com/stayallive/wp-sentry/blob/cd5505ab02c8f5df7407060fa9aa66a67c1ebf9a/src/class-wp-sentry-php-tracker.php#L132).

![Screenshot_20191028](https://user-images.githubusercontent.com/8146290/67672802-f6554880-f98d-11e9-87c7-6525b4c416d0.png)

**Comment by stayallive** [comment]
Add a `define('WP_SENTRY_VERSION', 'someversion')` to your `wp-config.php` for now to fix this without needing to change the plugin code.

I think this is going wrong:

```php
if ( ! defined( 'WP_SENTRY_VERSION' ) ) {
	define( 'WP_SENTRY_VERSION', wp_get_theme()->get( 'Version' ) );
}
```

Your theme might not have a proper version setup which causes `false` to be defined.

This will be fixed to default to something in the next version.

Thanks for letting me know! Will keep this open until the release is out.

**Comment by stayallive** [comment]
Version `v3.0.4` was just released to fix this!

**Comment by hossein** [comment]
Thanks for the fast update, and of course your plugin :+1:
