### ISSUE TITLE
Option to add callback function to JS options.

### ISSUE THREAD

**Issue by sigismund** [stayallive/wp-sentry#41]
Currently JS options can be edited using `wp_sentry_public_options` filter. Which works great for most of the options, but It would be even better if there was an option to add function like [beforeSend](https://docs.sentry.io/error-reporting/configuration/filtering/?platform=javascript).
This probably won't be achievable using current implementation, which uses ˙wp_localize_script`.

**Comment by stayallive** [comment]
This request was discussed in #42.
