### ISSUE TITLE
Add button to send test event

### ISSUE THREAD

**Issue by federicobond** [stayallive/wp-sentry#43]
This would help make sure that the integration is working as intended. I can submit a pull request if you are interested.

**Comment by stayallive** [comment]
That is most definitely not a terrible idea! 

WP UI is always a bit messy though 😉 

If a UI was to be added I would like it to live under "Tools" as "WP Sentry Test". It would be neat if it could indicate the following:

- If the PHP and/or JS tracker is active (basically if `WP_SENTRY_DSN` and/or `WP_SENTRY_PUBLIC_DSN` is not empty)
- The version that is transmitted to Sentry (`WP_SENTRY_VERSION`)
- The environment that is transmitted to Sentry (`WP_SENTRY_ENV`)

And ofcourse the test button which should generate a test event to sent to Sentry (something like [this](https://github.com/getsentry/sentry-laravel/blob/11a7de5342dabccbaaa45e4363596c000aab1e04/src/Sentry/Laravel/TestCommand.php#L56-L93)) and should report back the event id that Sentry reported.

---

What do you think? Sounds complete and useful and something you would be willing to work on?

**Comment by federicobond** [comment]
I just sent a pull request that addresses most of the stuff you mentioned. Let me know what you think!

**Comment by stayallive** [comment]
Just released `v3.2.0` which includes this. Thanks again for the PR!
