### ISSUE TITLE
Warning: Unsupported declare 'strict_types'

### ISSUE THREAD

**Issue by reggieofarrell** [stayallive/wp-sentry#46]
I'm getting 2 errors since the recent update...

```Warning: Unsupported declare 'strict_types' in /wp-content/plugins/wp-sentry-integration/vendor/zendframework/zend-diactoros/src/functions/create_uploaded_file.php on line 8```

...and... 

```Parse error: syntax error, unexpected ':', expecting '{' in /wp-content/plugins/wp-sentry-integration/vendor/zendframework/zend-diactoros/src/functions/create_uploaded_file.php on line 19```

...when running WP CLI commands.  Doesn't seem to be affecting the site in any way that I can tell.  I also think it is a hosting issue.  I'm using a VPS on DreamHost.  The PHP CLI version is `7.3`, but it could be an issue with their PHP and/or WP CLI setup.  I'm mostly putting this here for reference.  I'll update if DreamHost provides a fix as to what the actual issue was. 

Thanks for all the great work on this plugin.

**Comment by stayallive** [comment]
Hey @reggieofarrell thanks for providing this info, I don't think your site and/or WP CLI is running PHP 7.3... although if you are not a notice should be shown in the WP admin telling you the PHP version is too low for Sentry (7.1 is required).

So really interested in finding out what's what, keep me up-to-date with your findings!

**Comment by reggieofarrell** [comment]
There was some weirdness going on with the PHP CLI version.  It was showing me 7.3, but somehow it was still actually executing in 5.6.  DreamHost got it sorted out.

**Comment by stayallive** [comment]
Hey @reggieofarrell glad you got is resolved, thanks for the update 😄
