### ISSUE TITLE
PHP Fatal error v3.4.2

### ISSUE THREAD

**Issue by robgeorgeuk** [stayallive/wp-sentry#49]
This error occurred when plugin updated to 3.4.2.

```
[02-Apr-2020 01:42:38 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function WPSentry\ScopedVendor\GuzzleHttp\Psr7\uri_for() in /var/www/vhosts/mywebsite.org/httpdocs/wp-content/plugins/wp-sentry-integration/build/vendor/php-http/message/src/UriFactory/GuzzleUriFactory.php:19
Stack trace:
#0 /var/www/vhosts/mywebsite.org/httpdocs/wp-content/plugins/wp-sentry-integration/build/vendor/sentry/sentry/src/HttpClient/HttpClientFactory.php(99): WPSentry\ScopedVendor\Http\Message\UriFactory\GuzzleUriFactory->createUri('https://sentry....')
#1 /var/www/vhosts/mywebsite.org/httpdocs/wp-content/plugins/wp-sentry-integration/build/vendor/sentry/sentry/src/Transport/DefaultTransportFactory.php(42): Sentry\HttpClient\HttpClientFactory->create(Object(Sentry\Options))
#2 /var/www/vhosts/mywebsite.org/httpdocs/wp-content/plugins/wp-sentry-integration/build/vendor/sentry/sentry/src/ClientBuilder.php(238): Sentry\Transport\DefaultTransportFactory->create(Object(Sentry\Options))
#3 /var/www/vhosts/mywebsite.org/httpdocs/wp-content/plugins/wp-sentr in /var/www/vhosts/mywebsite.org/httpdocs/wp-content/plugins/wp-sentry-integration/build/vendor/php-http/message/src/UriFactory/GuzzleUriFactory.php on line 19
```

**Comment by koentjuh1** [comment]
Same here.

**Comment by robgeorgeuk** [comment]
Also the plugin seems to have updated itself as the update wasn't manually triggered nor updated by wpcli.
Does the plugin update itself?

**Comment by Jonakemon** [comment]
I get the same error, which is most likely caused by a Composer related issue with other WP plugins that also use Composer and the Guzzle library. I.e. I've been getting it with the mollie WooCommerce plugin that uses Composer as well.

For those working on this repository, maybe this can help you: https://github.com/mollie/WooCommerce/wiki/Composer-Guzzle-conflicts

**Comment by stayallive** [comment]
This plugin most certainly does not update itself, there is no mechanism to do this AFAIK and I have not built it either so I'm not sure what's going on there.

I did not find this perticulair error... I'm wondering what is happening...

I did change something recently to fix these type of conflicts but it looks like I might have created another issue: stayallive/wp-sentry#38.

Let me see if I can somehow replicate this, simply installing the Mollie plugin does not seems to cause this error unfortunately.

**Comment by Jonakemon** [comment]
> Let me see if I can somehow replicate this, simply installing the Mollie plugin does not seems to cause this error unfortunately.

Would it help if I give you access to my Sentry logs / PHP logs?

**Comment by stayallive** [comment]
Hi @Jonakemon not really :) I think I'm seeing the issue but I'm not sure what's causing it. Are you able to share a list of plugins (and their versions) so I can try to reproduce your installation to see if I can get the error locally and try to resolve it.

**Comment by Jonakemon** [comment]
Sure thing; I'll send you an email with the details.

**Comment by stayallive** [comment]
Much appreciated, thanks!

**Comment by indreek** [comment]
Here is my list

```
+---------------------------------------+----------+-----------+---------+
| name                                  | status   | update    | version |
+---------------------------------------+----------+-----------+---------+
| acf-gravityforms-add-on               | active   | none      | 1.2.1   |
| advanced-custom-fields-nav-menu-field | active   | none      | 2.0.0   |
| advanced-custom-fields-pro            | active   | none      | 5.8.9   |
| broken-link-checker                   | active   | none      | 1.11.12 |
| classic-editor                        | active   | none      | 1.5     |
| gravityforms                          | active   | none      | 2.4.17  |
| intuitive-custom-post-order           | active   | none      | 3.1.2   |
| redirection                           | active   | none      | 4.7.1   |
| regenerate-thumbnails                 | inactive | none      | 3.1.3   |
| simple-history                        | active   | none      | 2.33.2  |
| timber-library                        | active   | available | 1.9.4   |
| tinymce-advanced                      | inactive | none      | 5.2.1   |
| wordpress-importer                    | inactive | none      | 0.7     |
| wp-sentry-integration                 | inactive | none      | 3.4.2   |
| wpmandrill                            | active   | none      | 1.33    |
| sitepress-multilingual-cms            | active   | none      | 4.3.11  |
| wpml-string-translation               | active   | none      | 3.0.8   |
| wpml-translation-management           | active   | none      | 2.9.5   |
| wp-rocket                             | active   | none      | 3.5.2   |
| wordpress-seo                         | active   | none      | 13.4.1  |
| advanced-cache.php                    | dropin   | none      |         |
+---------------------------------------+----------+-----------+---------+,
```

**Comment by lkraav** [comment]
On my system, I see

```
plugins $ [-] find -type d -name GuzzleHttp
./fv-wordpress-flowplayer/includes/aws/GuzzleHttp
```

But deactivating this plugin doesn't help.

**Comment by stayallive** [comment]
I think I've found the issue (with the excellent help of humbug/php-scoper#298 and your information). 

I've reproduced the error and after the fixes I can't reproduce it anymore so I hope this will also fix the problems for all of you!

3.4.3 was just released with those changes, please do let me know if that helps!

**Comment by Jonakemon** [comment]
Error does not occur for me anymore! Thanks @stayallive! :)

**Comment by robgeorgeuk** [comment]
Thanks for the quick work @stayallive, this issue looks fixed for me too.

**Comment by stayallive** [comment]
Awesome!

Thank you all fot your patience and information 💪 and sorry for any problems caused.
