### ISSUE TITLE
Fatal error when used with Monolog 

### ISSUE THREAD

**Issue by selul** [stayallive/wp-sentry#50]
Hi, 

I have a custom logger based on Monolog which uses the wp-sentry client as one of the error handlers.

This is the Logger bootstrap code: 
```
                $logger = new MonologLogger( $this->logger_name );

		try {
			$logger->pushHandler( new ErrorLogHandler() );
			if ( defined( 'WP_SENTRY_DSN' ) &&
				 class_exists( '\WP_Sentry_Php_Tracker' ) &&
				 class_exists( '\Sentry\Monolog\Handler' )
			) {
				$client  = \WP_Sentry_Php_Tracker::get_instance()->get_client();
				$handler = new \Sentry\Monolog\Handler( $client, MonologLogger::WARNING );
				$logger->pushHandler( $handler );
			}
		} catch ( \Exception $e ) {
			error_log( 'Can not instantiate the logger.' );
		} 
```
Using the latest update, I'm getting a fatal error that seems to be related to a missing class inside the sentry build folder. 
The error can be found here -> https://sentry.io/share/issue/c89fad68bd5347f18c7f78daccaa2889/

I have used the 3.3.0 version before the update. 

Thanks a lot for your help!

**Comment by stayallive** [comment]
Jep this makes sense :)

It has nothing to do with a missing class though since the Sentry plugin does not ship with Monolog, so Monolog is coming from your dependencies but because of our scopeing the Monolog classes are namespaced although they shouldn't be.

Just released `v3.4.6`, let me know if the solved the issues for you!

**Comment by stayallive** [comment]
Have not heard from you for a bit so I'm going to assume my fix worked.

Please re-open if needed 👍

**Comment by selul** [comment]
Hi @stayallive,

Sorry, I forgot to confirm. Indeed, things are working fine now.

Thank you for your help!
