### ISSUE TITLE
3.5.0: WP_SENTRY_SEND_DEFAULT_PII true, but Sentry still shows only "user: ip:" field

### ISSUE THREAD

**Issue by lkraav** [stayallive/wp-sentry#53]
Since integration v3, I think I've lost the ability to display logged in user names in Sentry user context.

wp-config.php has `WP_SENTRY_SEND_DEFAULT_PII` true, but I still get only IP.

What am I missing?

https://github.com/stayallive/wp-sentry/search?q=get_current_user_info looks like it does the right thing, but... :man_shrugging:

**Comment by stayallive** [comment]
🤦 found the issue and fixed in `v3.5.1` which I just pushed out.

Thanks for reporting!
