### ISSUE TITLE
Wouldn't report with "new" DSN 

### ISSUE THREAD

**Issue by midwestE** [stayallive/wp-sentry#58]
Just setup the module and using the test page, sent a series of test exceptions.  They submit successfully, however are not visible on the sentry dashboard.  They are even given an event ID.

In looking up the DSN again to make sure it was correct, I found that there is a now a "Deprecated DSN" listed in the Client Keys section.  I changed the key to the Deprecated DSN and it is now reporting correctly and tests work.

![image](https://user-images.githubusercontent.com/6331501/83045935-e711a880-a00b-11ea-83a3-d17df6fffcbd.png)

**Comment by stayallive** [comment]
Can you share a bit more about your setup, which version of the plugin are you using? It should work with the new DSN just fine.

Are you also on sentry.io or do you have an onpremise setup?

**Comment by midwestE** [comment]
Using Version 3.6.0 and I'm using sentry.io.  When I first signed up for the account at sentry.io, it asked that I send an exception to "verify" the account, so I used the sentry test page to send it.  The strange thing is that it is getting an ID back on the submission but it just won't show on the sentry interface and wouldn't "verify".  Once I changed to the deprecated key it worked.

**Comment by stayallive** [comment]
Hmm, interesting, I just created a fresh project on sentry.io and defined the DSN (in the new format) like this:

```php
define('WP_SENTRY_DSN', 'https://xxx@xxx.ingest.sentry.io/xxx');
```

It took a few seconds after sending the test event but it definitely showed up.

Is it possible you might have pasted the wrong DNS (not copying it completely or adding a space or something)?

**Comment by midwestE** [comment]
Anything is possible!  One additional note, I had defined all constants in the read me in the wp-config.  We can choose this issue and if i can reproduce it, I'll reply here again.  Thanks for looking into it!

**Comment by stayallive** [comment]
I don't think if you only changed the DSN and it started working that the other defines had any effect on it. Hope you can try it again it see if it does work now with the short DSN, otherwise we will have to dig deeper.

**Comment by stayallive** [comment]
Oops, and I forgot to close the issue, of course feel free to re-open if you still have problems!

**Comment by antonioreyna** [comment]
i have the same issue it does not report and if i open the tester it says there is a problem

**Comment by antonioreyna** [comment]
nvm it was the curl library missing
