### ISSUE TITLE
Don't rename sentry .js on every version

### ISSUE THREAD

**Issue by kkmuffme** [stayallive/wp-sentry#60]
With every new version of sentry .js you also rename the sentry-browser min.js file.

When using a build pipeline that includes the sentry-browser min.js in a combined minified file one always also has to update the minification process with the new file name
Since you put custom, non-minified code in the .min.js anyway you don't really need it for versioning either.
And I assume everybody who uses sentry knows how to at least make sure their js expiry policy is managed in some way, making the file name versioning obsolete in this regard too.

**Comment by stayallive** [comment]
I appreciate the concern (and have done something similar in the past) but I don't want people depending on something in this plugin except for the public API. I am not doing it on purpose it just grew this way but I also can't be afraid to move some files around if I would want that :)

If you want to add the Sentry JS SDK to your build pipeline (in which I hope you do put it as the very first script) I would recommend just dequeuing it and copying the SDK JS to your own plugin/theme so you can bundle it from there.

You also should keep Sentry in the head if possible or at the very least as the first script to load on your page, so keeping it seperate might not be so bad. 

The Sentry SDK is already minified (except for the tiny integration bit at the end) so you don't gain much by bundling it, and assuming you have HTTP/2 available on your server it's probably better to have a few (not too much) separate JS files to load.

Last comment, most build pipelines support a `*` in filenames so include `wp-sentry-integration/public/sentry-browser-*.min.js` and you should be golden 👍 

---

> And I assume everybody who uses sentry knows how to at least make sure their js expiry policy is managed in some way, making the file name versioning obsolete in this regard too.

You'd be surprised, but that's a whole other topic 😉

**Comment by stayallive** [comment]
I wanted to update you on the situation, I've decided to change the filename one last time.

It will now become `wp-sentry-browser.min.js` and will be versioned only by the version parameter which will be synced by the plugin version instead of the Sentry Browser version.

This should solve your problem and possibly others in the future.

**Comment by kkmuffme** [comment]
Ok, I had already changed all my scripts, but will change it again so it matches your changes.
Thanks for the heads up
