### ISSUE TITLE
no valid js dsn error

### ISSUE THREAD

**Issue by rtpHarry** [stayallive/wp-sentry#62]
I've set this up:

![image](https://user-images.githubusercontent.com/1038062/84645642-c8128200-aef8-11ea-8974-3cdadafa6a0d.png)

With the same dsn for both `WP_SENTRY_DSN` and `WP_SENTRY_PUBLIC_DSN` but it's only recognising it for the PHP version.

I have the `WP_SENTRY_ENV` set up after and its recognising that line.

Here is the snippet:

```
// https://github.com/stayallive/wp-sentry/blob/master/README.md
define( 'WP_SENTRY_DSN', 'https://9b2033d01d3dea8604e5d569f5cae@o4032.ingest.sentry.io/51322' );
define( 'WP_SENTRY_PUBLIC_DSN', 'https://9b2033d01d3dea8604e5d569f5cae@o4032.ingest.sentry.io/51322' );
define( 'WP_SENTRY_ENV', 'production' );
```

(Deleted a few characters from each as it's not clear yet if this is supposed to be secret).

PHP is working and sent the test to Sentry successfully.

I was only wanting this for the javascript though! Any tips?

**Comment by rtpHarry** [comment]
I'm looking through the code and it's strange, I don't see it trying to load it from the `define` for the JS tracker?

PHP tracker explicitly checks for the defined var: https://github.com/stayallive/wp-sentry/blob/8141ad1a04fc0c052478acff1f95983680fb622d/src/class-wp-sentry-php-tracker.php#L96

But the JS class just checks the filter: https://github.com/stayallive/wp-sentry/blob/70930927eb1ad19a1aa753482a7c3123442e6f97/src/class-wp-sentry-js-tracker.php#L76

This is just initial investigation, maybe its set some other way but I can't find it in the code?

**Comment by rtpHarry** [comment]
OK I found that it is registered:

https://github.com/stayallive/wp-sentry/blob/70930927eb1ad19a1aa753482a7c3123442e6f97/wp-sentry.php#L85

I'm assuming then that the issue is that just putting this in my child theme functions.php is not enough.

**Comment by rtpHarry** [comment]
And there it is... :)

For anyone else that gets caught out like this in the future:

You have to put it in wp-config.php not your functions.php

**Comment by stayallive** [comment]
To be fair this is mentioned in the readme: https://github.com/stayallive/wp-sentry#configuration and in the installation instruction on WordPress plugins: https://wordpress.org/plugins/wp-sentry-integration/#installation 😉

**Comment by rtpHarry** [comment]
To be fair, that is a fair comment. :P

I don't know why I had it in my head it was functions.php, but at least there is a trail now for the next person that comes along.

**Comment by stayallive** [comment]
Haha no problem 😉 thanks for getting this in Google just in case 😄
