### ISSUE TITLE
e.dn is not a function

### ISSUE THREAD

**Issue by vermadarsh** [stayallive/wp-sentry#66]
Hi,

I've been using the [plugin](https://wordpress.org/plugins/wp-sentry-integration/) and recently we recorded a strange error oh which the screenshot is attached.

![sentry-error](https://user-images.githubusercontent.com/32696640/88371987-ba330500-cdb2-11ea-9235-f212c6494b65.png)

Please update if this can be fixed.

**Comment by stayallive** [comment]
Hi @vermadarsh this looks like either a bug in your code or possibly in the Sentry Browser integration, the error message is not telling my anything and without a stacktrace I cannot even begin to find out where it's coming from.

I did just release 3.10.0 which updates the browser integration, please check if it solves the issue.

If it does not fixes it please share more information about the error and it's origins and re-open this issue.
