### ISSUE TITLE
Browser Performance Monitoring / Tracing support

### ISSUE THREAD

**Issue by joejordanbrown** [stayallive/wp-sentry#67]
It would be nice to be able to use this plugin with the [Sentry Performance](https://docs.sentry.io/performance-monitoring/performance/) feature. 

I'm happy to create a pull request with this feature but would like to discuss first.

---------

Currently, we have to remove `wp-sentry-browser.min.js` which isn't straight forward because we want to keep the plugins `var wp_sentry = {...};`. 

We then include `https://browser.sentry-cdn.com/5.20.1/bundle.apm.min.js` and merge an extra options config with the plugins `wp_sentry` and then call `Sentry.init()`.

**Example:**
```
<script src="https://browser.sentry-cdn.com/5.20.1/bundle.apm.min.js" integrity="sha384-yRb6uqOrDZO0UoaXIwntp3rtwds2Zred8O/qjChDYuUX6ried457MYhtj1ASZEsX" crossorigin="anonymous"></script>
<script>
    var wp_sentry_extra = {
        'integrations': [
            new Sentry.Integrations.Tracing()
        ],
        'tracesSampleRate': '1'
    };
    Sentry.init( Object.assign( wp_sentry, wp_sentry_extra ) );
</script>
```

See the performance monitoring getting started docs [here](https://docs.sentry.io/performance-monitoring/getting-started/?platform=browser) for example code.

**Comment by stayallive** [comment]
Hi @joejordanbrown, I'm a bit partial to this but I think we have to take another route for this.

I would maybe go for adding another constant you can set in the `wp-config.php` named something like `SENTRY_BROWSER_APM_SAMPLE_RATE` which if higher than `0` will _switch_ to the bundle file with APM included.

Does that sound good like a good solution? I don't want to force APM stuff onto anyone so the default should be it not including any APM related code if possible and only use the APM bundle if the user requested that.

**Comment by joejordanbrown** [comment]
Hello @stayallive, Thanks for the great plugin.

My example was only how we are currently working around injecting the code dynamically on page load. It wasn't how I would expect it to be in this plugin. I don't expect anyone to be forced to use APM script, also this plugin needs to stay backwards compatible so I don't expect the default functionality to change when adding this feature.

Yes for the average user your option is fine to add a new constant that switches the script etc.

But I do think we need a way to extend this plugin without having to keep using constants because it's very limiting to use all the sentry features. Also a pain for you having to modify this plugin each time for new integrations etc.

It would be good to have options to include the sentry script using your custom version (by default), and optionally to use the default sentry (not modified version), the APM bundle version or even a custom sentry script URL.

Using the filter `wp_sentry_public_options` is limited and is not a good way for us to add javascript options because we need to call JavaScript functions which end up being strings.

The best option in my eyes is a new hook to allow us to inject our own JavaScript after the sentry script is enqueued, which allows us to call `Sentry.init()` ourself instead of automatically being called with your custom `wp-sentry-browser.min.js`. Enabling us to merge our own options with the plugins options. We still want the default `var wp_sentry = {...};` that this plugin sets.

All this would be backwards compatible and would allow anyone to extend the JavaScript sentry options.

**Comment by joejordanbrown** [comment]
In short, we would just need to be able to customise this 

https://github.com/stayallive/wp-sentry/blob/master/src/class-wp-sentry-js-tracker.php#L150-L155

**Comment by joejordanbrown** [comment]
@stayallive 

Any update on adding the feature to allow us to provide our own javascript browser file like shown above using for example SENTRY_BROWSER_SCRIPT?

I don't mind providing a pull request for this feature, it won't create any backwards compatibility issues.

**Comment by stayallive** [comment]
I have opted to go another route.

If you want to replace the Sentry browser script just disable ours and enqueue your own 😄 

But we now have a `WP_SENTRY_BROWSER_TRACES_SAMPLE_RATE` option to enable Sentry browser tracing with the default options.

**Comment by stayallive** [comment]
I feel like we solved this one and browser performance monitoring is available with some options to configure it. If there are specific things that are not working or not supported please open up a new issue so we can investigate!
