### ISSUE TITLE
Simple and straight-forward main plugin file

### ISSUE THREAD

**Issue by szepeviktor** [stayallive/wp-sentry#70]
If every WordPress installation would run in a [strictly controlled](https://github.com/szepeviktor/debian-server-tools/blob/master/Onboarding.md) and Composer-managed environment
wp-sentry.php could be only a couple of lines long without any conditionals.

# 😿

**Comment by stayallive** [comment]
Yes. I'm not sure if you were looking for something here but I can't fix WordPress so this is how it is for now.
