### ISSUE TITLE
Suggestion: use wp_get_environment_type to set WP_SENTRY_ENV

### ISSUE THREAD

**Issue by ictbeheer** [stayallive/wp-sentry#71]
WP 5.5 introduced the new function https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/

This could be used to set the environment if WP_SENTRY_ENV is not defined yet.

**Comment by stayallive** [comment]
This is an excellent idea, I was not aware of that addition but sounds like a sane default 👍
