### ISSUE TITLE
wp_sentry_options filter is never used

### ISSUE THREAD

**Issue by Kilbourne** [stayallive/wp-sentry#73]
Currently the only place where the filter is called is:
https://github.com/stayallive/wp-sentry/blob/9e21376b681ce5176202df97336cfd62b1cc0f4f/src/class-wp-sentry-php-tracker.php#L85-87
```
                // Apply the filter to configure any options
		if ( has_filter( 'wp_sentry_options' ) ) {
			apply_filters( 'wp_sentry_options', $this->get_client()->getClient()->getOptions() );
		}
```

This is after this commit [Remove filter from default options ](https://github.com/stayallive/wp-sentry/commit/94460cb3b70ab324dc52012841919290253340c3), although i can't see why you did it..

**Comment by Kilbourne** [comment]
OK sorry, misread the docs ( but probably is more appropiate a 'do_action' to make clearer the return value has no effect)

**Comment by stayallive** [comment]
Yes, it probably should, however it works and is documented so to prevent breaking code I'll leave it in for now.

If you feel like the docs should be more clear feel free to submit a PR 😄
