### ISSUE TITLE
[3.11.0] Fatal error: Trait 'WP_Sentry_Resolve_Environment'

### ISSUE THREAD

**Issue by chggib** [stayallive/wp-sentry#74]
Just tried to use the newest version and received the following:

Fatal error: Trait 'WP_Sentry_Resolve_Environment' not found in .../plugins/wp-sentry-integration/src/class-wp-sentry-php-tracker.php on line 13

WordPress version: 5.5.3
WordPress Sentry: version: 3.11.0, author: Alex Bouma
php_version: 7.2.34 64bit

Let me know if you need other info / if there is something I need to do on my end.

Thanks

**Comment by tylertadej** [comment]
Same.. my WP site auto-updated this plugin and it created a fatal error which took the site down.

**Comment by stayallive** [comment]
Unfortunately there was something wrong with the release process which I missed :( It looks like the setup PHP command for GitHub actions has auto-upgraded to use Composer v2 which prevented the release to be completely built.

I'm sorry this happened, version `3.11.1` is rolling out which fixes that!

**Comment by tylertadej** [comment]
@stayallive thanks for the quick fix! Updated and verified as working.

**Comment by stayallive** [comment]
Thanks for verifying and again apologies (to everyone affected) for this, will make sure to add safe guards against this happening again in the future.
