### ISSUE TITLE
Upgrade sentry-php

### ISSUE THREAD

**Issue by clintonb** [stayallive/wp-sentry#78]
I received an email from Sentry noting my use of the outdated Sentry library. What work is needed to go from 2.x to 3.x?

**Comment by therajumandapati** [comment]
Just got received the same email. How can we help @stayallive ?

**Comment by stayallive** [comment]
Oh wow nice heads up about this e-mail being sent, lol 🥇 

Out of curiosity could you share the e-mail text here (keep your personal information out of it, just interested in the text)?

I'm going to make an effort to get an update out for you guys with the new PHP SDK, hold tight! 😉

**Comment by therajumandapati** [comment]
@stayallive Here's the screenshot of the email: 
![image](https://user-images.githubusercontent.com/5555261/106007460-54fefa00-60dc-11eb-8dfd-4a83c99b6832.png)

**Comment by stayallive** [comment]
Just for future readers having a bit of a panic because of this e-mail.

> There is no reason to immediately NEEDING to upgrade because it won't stop working tomorrow or something

But I am working on the update and hope to get that in your hands soon!

**Comment by stayallive** [comment]
After a little snafoo [4.0.0](https://github.com/stayallive/wp-sentry/releases/tag/v4.0.0) was just released (but you will install [4.0.1](https://github.com/stayallive/wp-sentry/releases/tag/v4.0.1) which uses the new SDK.

If you done any custom interaction with the plugin please make sure it works before blindly updating 😉
