### ISSUE TITLE
Uncaught Error: Undefined constant 'CURLOPT_TIMEOUT'

### ISSUE THREAD

**Issue by LucianoHanna** [stayallive/wp-sentry#80]
Environment:
Ubuntu 20.04
php 7.4.3

Fatal error: 
Uncaught Error: Undefined constant 'CURLOPT_TIMEOUT' in /var/www/html/wp-content/plugins/wp-sentry-integration/build/vendor/sentry/sentry/src/HttpClient/HttpClientFactory.php:113
Stack trace:
#0 /var/www/html/wp-content/plugins/wp-sentry-integration/build/vendor/sentry/sentry/src/Transport/DefaultTransportFactory.php(57): Sentry\HttpClient\HttpClientFactory-&gt;create()
#1 /var/www/html/wp-content/plugins/wp-sentry-integration/build/vendor/sentry/sentry/src/ClientBuilder.php(149): Sentry\Transport\DefaultTransportFactory-&gt;create()
#2 /var/www/html/wp-content/plugins/wp-sentry-integration/build/vendor/sentry/sentry/src/ClientBuilder.php(137): Sentry\ClientBuilder-&gt;createTransportInstance()
#3 /var/www/html/wp-content/plugins/wp-sentry-integration/src/class-wp-sentry-php-tracker.php(179): Sentry\ClientBuilder-&gt;getClient()
#4 /var/www/html/wp-content/plugins/wp-sentry-integration/src/class-wp-sentry-php-tracker.php(116): WP_Sentry_Php_Tracker-&gt;initializeClient()
#5 /var/www/html/wp-content/plugins/wp-sentry-integra in  /var/www/html/wp-content/plugins/wp-sentry-integration/build/vendor/sentry/sentry/src/HttpClient/HttpClientFactory.php on line 113

**Comment by stayallive** [comment]
Have you installed the curl PHP extension?

**Comment by LucianoHanna** [comment]
It was that, thank you.
