### ISSUE TITLE
Sentry on Premise

### ISSUE THREAD

**Issue by robsonsobral** [stayallive/wp-sentry#83]
Hi!

Please, how do I set the `SENTRY_URL` pointing to a self hosted Sentry instance?

Thank you for your attention!

**Comment by stayallive** [comment]
It the DSN option you are looking for. 

A self-hosted Sentry generates a DSN just like sentry.io and you don't have to do anything else to make it work with a self-hosted instance. Enter the DSN and you're good to go. 

But it's more useful for you to tell me what you did and what is not working 👌

**Comment by robsonsobral** [comment]
I'm sorry, @stayallive ! I guess I need to sleep more and work a little less. But I'm not sure about it!

Thank you so much!
