### ISSUE TITLE
Bug: PHP errors are not getting reported anymore

### ISSUE THREAD

**Issue by kkmuffme** [stayallive/wp-sentry#91]
Sentry is not triggering/recording errors since 4.4.1 (maybe 4.4.0) anymore.

In 4.3.0 I got sentry errors for:

```php
call_this();
exit;
```

or

```php
echo $helloworld;
exit;
```

In 4.4.1 they wont show up in sentry.

**Comment by stayallive** [comment]
Can you confirm that downgrading fixes the problem?

**Comment by kkmuffme** [comment]
Yes, it works in 4.3.0, I just tested it again.

**Comment by stayallive** [comment]
Hmm, I have been trying to reproduce this but when using your code in `header.php` of the Twenty Seventeen theme I get the reports sent to Sentry every time.

Can you tell me a bit more about your PHP version and environment (Linux/Windows) and where exactly you are placing that code?

The code placement should not matter as long as you don't move it between testing between 4.3.0 and 4.4.x of course but just wanting to make sure.

**Comment by kkmuffme** [comment]
Just updated to 4.5.0 and it works again.

Looks like a bug in the sentry lib used in 4.4.0/4.4.1.

**Comment by stayallive** [comment]
Okay interesting, but glad it's working at least 👌
